### ISSUE TITLE
Uncaught TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by steentje34** [ctsit/move_data_to_other_event#2]
Using the external module in a project with Custom Event Labels or repeating events throws a JavaScript error:
![image](https://user-images.githubusercontent.com/29727779/66920296-47c31680-f023-11e9-86c5-1525e563751b.png)

In both cases, the first child of the actual element is not what the external module expects.
https://github.com/ctsit/move_data_to_other_event/blob/be87a53a9f5575279105b6a5b05f1b612ee64f2a/js/mdoe.js#L22

**Comment by marlycormar** [comment]
This issue was partially addressed by PR #3: the module now works with custom event levels.

**Comment by pbchase** [comment]
closed by PR #3
