### ISSUE TITLE
Issue moving data to first form on first event 

### ISSUE THREAD

**Issue by marlycormar** [ctsit/move_data_to_other_event#8]
Moving data from any event to the first form on the first event doesn't delete the data on the originating form.

**Comment by pbchase** [comment]
@ChemiKyle, says this likely arises from the intentional blocking of moving data from form 1 event 1. This was blocked in commit 82cc5b4 because the record's primary key is considered an entry in form 1 event 1; there is now an exclusion of record primary key in movement actions and is no longer needed.

**Comment by ChemiKyle** [comment]
Unfortunately simply turning off [skipping the first form](https://github.com/ctsit/move_data_to_other_event/blob/9624b5a5fb436521e513b76e7cfef4094b0d86b8/js/mdoe.js#L33) is not a panacea.  
Cloning works fine, but moving data - either to or from form 1 event 1 - results in an error during [deletion](https://github.com/ctsit/move_data_to_other_event/blob/9624b5a5fb436521e513b76e7cfef4094b0d86b8/ExternalModule.php#L85). Strangely, this also causes the target field to be written to twice, and while the origin event may not have entries in the database, some fields _still appear populated in the frontend_ for that event and form.

UPDATE  
The latter issue appears even without using the module. I am providing the project XML to recreate this issue. I am using REDCap 9.4.1.  
Steps:
1. Add new record.
2. Fill in data for _any_ form on _any_ event other than the first, save & exit
3. Fill in all fields in form 1, event 1, save & exit
4. Open form 1 on the final event, observe that the `email` field is already populated

[Events_2019-10-31_1214.REDCap.xml.zip](https://github.com/ctsit/move_data_to_other_event/files/3975067/Events_2019-10-31_1214.REDCap.xml.zip)

**Comment by pbchase** [comment]
closed by PR #9
